name: updatecli
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every hour
    - cron: '0/5 * * * *'
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2"

      - uses: tibdex/github-app-token@v1.6
        id: generate_token
        if: github.ref == 'refs/heads/main'
        with:
          app_id: ${{ secrets.UPDATECLIBOT_APP_ID }}
          private_key: ${{ secrets.UPDATECLIBOT_APP_PRIVKEY }}

      - name: Login with Udash
        run: "updatecli udash login --experimental --oauth-access-token $UDASH_ACCESS_TOKEN $UDASH_URL"
        env:
          UDASH_ACCESS_TOKEN: ${{ secrets.UDASH_ACCESS_TOKEN }}
          UDASH_URL: ${{ vars.UDASH_URL }}

      - name: "Run updatecli"
        run: "updatecli apply --config ./updatecli/updatecli.d --experimental"
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ secrets.UPDATECLI_BOT_GITHUB_ACTOR }}
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Logout from Udash
        run: "updatecli udash logout --experimental $UDASH_URL"
        env:
          UDASH_URL: ${{ vars.UDASH_URL }}

